import { describe, it, expect, beforeEach } from 'vitest';
import { GameMaster } from '../src/GameMaster';
import { MockAdapter } from '@llmrpg/llm';
import { SessionWriter, SessionLoader, FileSystemAdapter } from '@llmrpg/storage';
import path from 'path';
import fs from 'fs';

const STORAGE_PATH = path.join(__dirname, '../test-sessions');

describe('Compel System', () => {
  let gm: GameMaster;
  let mockLLM: MockAdapter;
  let sessionWriter: SessionWriter;
  let sessionLoader: SessionLoader;
  let sessionId: string;

  beforeEach(async () => {
    sessionId = `compel-test-${Date.now()}`;
    
    if (!fs.existsSync(STORAGE_PATH)) {
      fs.mkdirSync(STORAGE_PATH, { recursive: true });
    }
    
    const fsAdapter = new FileSystemAdapter(STORAGE_PATH);
    sessionWriter = new SessionWriter(fsAdapter);
    sessionLoader = new SessionLoader(fsAdapter);
    
    await sessionWriter.createSession(sessionId, {
      startTime: Date.now(),
      player: 'Test Player'
    });
    
    mockLLM = new MockAdapter();
    gm = new GameMaster(sessionId, mockLLM, sessionWriter, sessionLoader);
    
    await gm.initializeWorld('Dark Fantasy');
    await gm.createCharacter('A stubborn warrior with a dark past');
    
    // Add trouble aspect and set FP
    if ((gm as any).player) {
      (gm as any).player.aspects.push({
        id: 'aspect-trouble',
        name: 'Trouble: Short Tempered',
        type: 'trouble',
        description: 'Prone to anger',
        freeInvokes: 0
      });
      (gm as any).player.fatePoints.current = 3;
    }
    
    await gm.start();
  });

  it('should offer a compel when generated by DecisionEngine', async () => {
    const mockCompel = {
      aspectName: 'Trouble: Short Tempered',
      type: 'decision',
      description: 'Your anger flares up at the insult.'
    };
    
    (gm as any).decisionEngine.generateCompel = async () => mockCompel;
    (gm as any).decisionEngine.classifyIntent = async () => 'fate_action';
    
    const result = await gm.processPlayerAction('I try to negotiate calmly.') as any;
    
    expect(result.result).toBe('compel_offered');
    expect(result.compel).toBeDefined();
    expect(result.compel.aspectName).toBe('Trouble: Short Tempered');
  });

  it('should award FP when compel is accepted', async () => {
    const mockCompel = {
      aspectName: 'Trouble: Short Tempered',
      type: 'decision',
      description: 'Your anger flares up.'
    };
    
    (gm as any).decisionEngine.generateCompel = async () => mockCompel;
    (gm as any).decisionEngine.classifyIntent = async () => 'fate_action';
    
    const result = await gm.processPlayerAction('I try to negotiate calmly.') as any;
    
    const initialFP = (gm as any).player?.fatePoints.current || 0;
    
    const acceptResult = await gm.resolveCompel(result.compel!, true);
    
    expect(acceptResult.result).toBe('compel_accepted');
    expect((gm as any).player?.fatePoints.current).toBe(initialFP + 1);
  });

  it('should deduct FP when compel is refused', async () => {
    const mockCompel = {
      aspectName: 'Trouble: Short Tempered',
      type: 'decision',
      description: 'Your anger flares up.'
    };
    
    (gm as any).decisionEngine.generateCompel = async () => mockCompel;
    (gm as any).decisionEngine.classifyIntent = async () => 'fate_action';
    
    const result = await gm.processPlayerAction('I try to negotiate calmly.') as any;
    
    const initialFP = (gm as any).player?.fatePoints.current || 0;
    
    const refuseResult = await gm.resolveCompel(result.compel!, false);
    
    expect(refuseResult.result).toBe('compel_refused');
    expect((gm as any).player?.fatePoints.current).toBe(initialFP - 1);
  });

  it('should skip compel check when flag is set', async () => {
    const mockCompel = {
      aspectName: 'Trouble: Short Tempered',
      type: 'decision',
      description: 'Your anger flares up.'
    };
    
    (gm as any).decisionEngine.generateCompel = async () => mockCompel;
    (gm as any).decisionEngine.classifyIntent = async () => 'fate_action';
    (gm as any).decisionEngine.classifyAction = async () => 'overcome';
    (gm as any).decisionEngine.selectSkill = async () => ({ name: 'Rapport', rating: 2 });
    (gm as any).decisionEngine.setOpposition = async () => 2;
    (gm as any).decisionEngine.identifyTarget = async () => null;
    (gm as any).decisionEngine.determineKnowledgeGain = async () => null;
    (gm as any).decisionEngine.determineQuestUpdate = async () => null;
    (gm as any).decisionEngine.determineWorldUpdates = async () => [];
    
    const result = await gm.processPlayerAction('I try to negotiate calmly.', undefined, true) as any;
    
    expect(result.result).not.toBe('compel_offered');
  });
});
